# Naive Bayes Algoritam

Da razjasnimo:

### 🔹 CategoricalNB
- radi sa **diskretnim kategorijama**
- očekuje vrednosti tipa: `0, 1, 2, ...`
- ne zanima ga redosled ni veličina

➡️ *„Koja kategorija je prisutna?“*

### 🔹 MultinomialNB
- radi sa **brojanjima**
- očekuje **koliko puta se nešto pojavilo**
- savršen za **TF / TF-IDF matrice**

➡️ *„Koliko puta se reč pojavila u dokumentu?“*


In [130]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 1.4085999999977648 seconds
All requested packages already installed.


In [9]:
!mamba install scikit-learn

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 1.032199999999255 seconds
  Name                          Version                       Build                         Channel                       
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ brotli-python                 1.2.0                         py313h33caa6c_0               emscripten-forge              
+ certifi                       2026.1.4                      pyhd8ed1ab_0                  conda-forge                   
+ charset-normalizer            3.4.4                         pyhd8ed1ab_0                  conda-forge                   
+ idna                          3.11                          pyhd8ed1ab_0                  conda-forge                   
+ joblib                        1.5.3 

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('balloons.csv')

In [5]:
df

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  CHILD        F
3   YELLOW  SMALL      DIP  ADULT        F
4   YELLOW  SMALL      DIP  CHILD        F
..     ...    ...      ...    ...      ...
71  PURPLE  SMALL      DIP  CHILD        F
72  PURPLE  LARGE  STRETCH  ADULT        F
73  PURPLE  LARGE  STRETCH  CHILD        F
74  PURPLE  LARGE      DIP  ADULT        F
75  PURPLE  LARGE      DIP  CHILD        F

[76 rows x 5 columns]

In [42]:
X = df.drop('inflated', axis=1) #ulazne
y = df['inflated']              #ciljna

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
# pisemo sa malim y!!!
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=123)

Pre korišćenja **CategoricalNB** modela potrebno je da se kategoricki atributi
sa $n_i$ kategorija mapiraju u numeričke vrednosti $0, 1, \ldots, n_i - 1$.

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
#oe = OrdinalEncoder() ovo radi na ispitu :)
oe = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)

Kao i obično, fit samo na trening skupu:

In [47]:
oe.fit(X_train)

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [48]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [49]:
from sklearn.naive_bayes import CategoricalNB

In [50]:
model = CategoricalNB()

In [51]:
model.fit(X_train, y_train)

CategoricalNB()

In [52]:
model.category_count_

[array([[18., 11.],
        [ 8., 16.]]),
 array([[17., 12.],
        [ 6., 18.]]),
 array([[20.,  9.],
        [ 7., 17.]]),
 array([[11., 18.],
        [15.,  9.]])]

In [53]:
model.class_count_

array([29., 24.])

Na osnovu ove dve stvari računamo verovatnoću **P( y | X )** i predviđamo klasu.

In [54]:
y_train_pred = model.predict(X_train)

In [55]:
y_test_pred = model.predict(X_test)

In [58]:
from sklearn.metrics import confusion_matrix

In [59]:
confusion_matrix(y_train, y_train_pred)

array([[25,  4],
       [ 9, 15]], dtype=int64)

In [60]:
confusion_matrix(y_test, y_test_pred)

array([[9, 3],
       [3, 8]], dtype=int64)

-----------------------------------------

<h2> Klasifikacija teksta

<h3> TF matrica

In [62]:
import pandas as pd

In [63]:
data = pd.read_csv('20newsgroups.csv')

In [65]:
data.head()

text  target
0  \n\nI am sure some bashers of Pens fans are pr...      10
1  My brother is in the market for a high-perform...       3
2  \n\n\n\n\tFinally you said what you dream abou...      17
3  \nThink!\n\nIt's the SCSI card doing the DMA t...       3
4  1)    I have an old Jasmine drive which I cann...       4

In [79]:
data.isna().any()

text       True
target    False
dtype: bool

In [86]:
data.dropna(inplace=True)

In [87]:
data.isna().any()

text      False
target    False
dtype: bool

1️⃣ **Šta u ovom skupu igra ulogu “teksta”?**

U 20 Newsgroups datasetu imaš:

- jednu kolonu sa **tekstom dokumenta** (često se zove text, content, message ili slično)

- jednu kolonu sa **kategorijom / grupom** (npr. target, group, label)

`TF matrica se pravi` **`ISKLJUČIVO`** `iz tekstualne kolone.`

2️⃣ **Ideja TF matrice (u jednoj rečenici)**

TF matrica broji **koliko se puta svaka reč pojavljuje u svakom dokumentu**.

- red = dokument

- kolona = reč

vrednost = broj pojavljivanja reči u tom dokumentu

4️⃣ **Formiranje TF matrice (NAJBITNIJI DEO)**

Za TF matricu se koristi CountVectorizer iz sklearn-a.

In [128]:
X = data['text']   # tekstualni dokumenti, ulazni 
y = data['target'] # ciljni

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,stratify=y)

In [116]:
from sklearn.feature_extraction.text import CountVectorizer

In [117]:
vectorizer = CountVectorizer()

In [118]:
X_train_tf = vectorizer.fit_transform(X_train)

In [119]:
X_test_tf  = vectorizer.transform(X_test)

<h4>Primena <b>MultinominalNB</b> nad TF:

In [120]:
from sklearn.naive_bayes import MultinomialNB

In [121]:
model = MultinomialNB()

In [122]:
model.fit(X_train_tf, y_train)

MultinomialNB()

In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [127]:
y_pred = model.predict(X_test_tf)

cm  = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
f1  = f1_score(y_test, y_pred, average='macro')

#cm, acc, f1

<h3>TF-IDF matrica

> umesto CountVectorizer koristimo `TfidfVectorizer`

In [131]:
X = data['text']   # tekstualni dokumenti, ulazni 
y = data['target'] # ciljni

In [132]:
from sklearn.model_selection import train_test_split

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,stratify=y)

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [136]:
vectorizer = TfidfVectorizer()

In [137]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [138]:
X_test_tfidf  = vectorizer.transform(X_test)

<h4>Primena <b>MultinominalNB</b> nad TF-IDF:

In [139]:
from sklearn.naive_bayes import MultinomialNB

In [140]:
model = MultinomialNB()

In [141]:
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [142]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [145]:
y_pred = model.predict(X_test_tfidf)

cm  = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
f1  = f1_score(y_test, y_pred, average='macro')

#cm, acc, f1